Repository jamesbraza/cs231n-3d-segmentation, pull requests merged in 2023-06, with the labels that each got.

#4 Fixing results visualization
  .pre-commit-config.yaml
  baseline/training_utils.py
  baseline/unet_training.py
Labels: bug

#5 Fixing GIF creation
  baseline/training_utils.py
Labels: bug

#6 `BraTS2020Dataset` and `pytorch-3dunet` integration
  .pre-commit-config.yaml
  README.md
  baseline/autoencoder_data.py
  baseline/autoencoder_training.py
  baseline/requirements.txt
  baseline/unet_data.py
  baseline/unet_training.py
  data/loaders.py
  requirements-qa.txt
  requirements.in
  requirements.txt
  unet_zoo/.gitignore
  unet_zoo/__init__.py
  unet_zoo/train.py
Labels: enhancement

#7 Functioning pytorch-3dunet training
  data/loaders.py
  unet_zoo/train.py
Labels: bug

#8 Lightweight training and training docs
  data/loaders.py
  requirements.in
  requirements.txt
  unet_zoo/train.py
Labels: enhancement

#9 VM training tweaks
  README.md
  unet_zoo/train.py
Labels: enhancement

#10 Training with metrics
  .pre-commit-config.yaml
  data/loaders.py
  unet_zoo/train.py
Labels: enhancement

#11 Longer training
  .pre-commit-config.yaml
  README.md
  unet_zoo/train.py
Labels: enhancement

#12 3.11 in VM and better TensorBoard docs
  README.md
Labels: documentation

#13 Latest `matplotlib`
  baseline/training_utils.py
  requirements.in
  requirements.txt
Labels: bug

#14 Added `gif-your-nifti`
  README.md
  requirements.in
  requirements.txt
Labels: enhancement

#15 `BraTS2020Dataset` validations
  data/loaders.py
  requirements.in
  requirements.txt
Labels: enhancement

#16 Prediction beginnings
  pyproject.toml
  requirements.in
  requirements.txt
  unet_zoo/.gitignore
  unet_zoo/__init__.py
  unet_zoo/predict.py
  unet_zoo/train.py
  unet_zoo/utils.py
Labels: enhancement

#17 2D U-Net preparation
  data/loaders.py
  pyproject.toml
  unet_zoo/train.py
Labels: enhancement

#18 `UNet2D` training compatibility
  data/loaders.py
  unet_zoo/predict.py
  unet_zoo/train.py
Labels: enhancement

#19 Resetting of `BraTS2020MRISlicesDataset` across iterations
  data/loaders.py
  requirements.in
  unet_zoo/train.py
Labels: bug

#20 Prediction summary visualization and seeded datasets
  data/loaders.py
  unet_zoo/predict.py
  unet_zoo/train.py
  unet_zoo/utils.py
Labels: enhancement

#21 input tensor type is cuda to match with weight tensor type
  baseline/unet_training.py
Labels: bug

#22 Plotting three views actual vs preds
  .pre-commit-config.yaml
  unet_zoo/predict.py
  unet_zoo/utils.py
Labels: enhancement

#24 `sweep_thresholds` working results and `MeanIoU`
  .pre-commit-config.yaml
  unet_zoo/metrics.py
  unet_zoo/predict.py
Labels: enhancement

#25 Fixing `MeanIoU` binarize condition and non-multi-channel plotting logic
  unet_zoo/metrics.py
  unet_zoo/predict.py
Labels: bug

#26 Visualization tweaks
  baseline/unet_training.py
  baseline/visualize.py
  unet_zoo/predict.py
Labels: enhancement

#27 80%, 10%, 10% split
  unet_zoo/predict.py
  unet_zoo/train.py
Labels: enhancement

#29 Saving prediction summaries
  unet_zoo/.gitignore
  unet_zoo/__init__.py
  unet_zoo/predict.py
Labels: enhancement

#30 Fix of summary plots batching
  unet_zoo/predict.py
Labels: bug

#31 `make_summary_plots` running on VM
  unet_zoo/predict.py
  unet_zoo/utils.py
Labels: bug

#32 `WT`, `TC`, `ET` constants
  data/loaders.py
  unet_zoo/predict.py
  unet_zoo/train.py
Labels: enhancement

#33 3-D Visualization
  README.md
  data/loaders.py
  pyproject.toml
  requirements.in
  requirements.txt
  unet_zoo/predict.py
Labels: enhancement

#34 Sweep threshold's plot tweaks
  unet_zoo/predict.py
Labels: enhancement

#35 README summary section
  README.md
  docs/assets/labels_ex2_ear(60, 210, 300).png
  docs/assets/unet2d_inference_ex2_angle0.png
  docs/assets/unet2d_inference_ex2_angle1.png
  docs/assets/unet2d_inference_ex2_angle2.png
  docs/assets/unet2d_predictions_ex2_ear(60, 210, 300).png
  docs/assets/unet3d_inference_ex2_angle0.png
  docs/assets/unet3d_inference_ex2_angle1.png
  docs/assets/unet3d_inference_ex2_angle2.png
  docs/assets/unet3d_predictions_ex2_ear(60, 210, 300).png
Labels: documentation
